actor client
participant hda_dma

client -> hda_dma : dma_copy()
	activate hda_dma
	note right: FPI is updated

	hda_dma -> hda_dma : verify next period is available in the local buffer
	hda_dma -> client : callback()
		activate client
		client -> client : comp_update_buffer_produce/consume()
	hda_dma <-- client
	deactivate client

	hda_dma -> hda_dma : update notification ptr

client <-- hda_dma
deactivate hda_dma
