actor client
participant hda_dma
participant work_queue

client -> hda_dma : dma_start()
	activate hda_dma
	note right: GEN := 1 -> transfer starts

	hda_dma -> work_queue : work_schedule_default(&hda_work, HDA_HOST_TX_DELAY_US)
	hda_dma <-- work_queue
client <-- hda_dma
deactivate hda_dma

... First data from host is coming ...

work_queue -> hda_dma : hda_work->cb()
	activate hda_dma
	hda_dma -> hda_dma : wait for first period to be completed (w/ short t/o)

	hda_dma -> client : callback()
		activate client
		client -> client : comp_update_buffer_produce()
	hda_dma <-- client
	deactivate client

	hda_dma -> hda_dma : update notification ptr

work_queue <-- hda_dma
deactivate hda_dma
