actor client
participant hda_dma
participant work_queue

client -> hda_dma : dma_start()
	activate hda_dma
	note right: GEN := 1 -> transfer starts

	hda_dma -> work_queue : work_schedule_default(&hda_work, HDA_LINK_1MS_US)
	hda_dma <-- work_queue
client <-- hda_dma
deactivate hda_dma

... 1 ms elapsed ...

work_queue -> hda_dma : hda_work->cb()
	activate hda_dma
	hda_dma -> hda_dma : wait for next period to be available (w/ short t/o)

	hda_dma -> client : callback()
		activate client
		client -> client : comp_update_buffer_produce/consume()
		client -> client : update *next
	hda_dma <-- client
	deactivate client

	hda_dma -> hda_dma : update FPI with data from *next

	hda_dma -> hda_dma : update notification ptr

	opt cyclic
		hda_dma -> work_queue : work_schedule_default(...)
		note right: re-arm the timer for next 1ms (- time elapsed in cb)
	end opt
work_queue <-- hda_dma
deactivate hda_dma
